ops:
  compose_queries:
    config:
      year_id:
        env: POWERSCHOOL_YEAR_ID
      tables:
        - name: schools
        - name: students
          queries:
            - projection: student_number,lastfirst          
        - name: cc
          queries:
            - q:
                selector: termid
                value: 3100
            - q:
                selector: termid
                value: -3100
        - name: log
          queries:
            - q:
                selector: entry_date
