resources:
  powerschool:
    config:
      host:
        env: POWERSCHOOL_HOST
      client_id: 
        env: POWERSCHOOL_CLIENT_ID
      client_secret:
        env: POWERSCHOOL_CLIENT_SECRET
  gcs_io:
    config:
      gcs_prefix: powerschool
execution:
  config:
    multiprocess:
      max_concurrent: 50