resources:
    mssql:
        config:
            dialect: mssql
            driver: pyodbc
            mssql_driver: "ODBC Driver 17 for SQL Server"
            username:
                env: MSSQL_USERNAME
            password:
                env: MSSQL_PASSWORD
            host:
                env: MSSQL_HOST
            port:
                env: MSSQL_PORT
            database:
                env: MSSQL_DATABASE
