---
ops:
  queries_to_execute:
***REMOVED***
      year_id: 31
      queries:
      - table_name: schools
      - table_name: students
        projection: student_number,lastfirst
      - table_name: cc    
        q:
          selector: termid
          value: -3100
      - table_name: log
        q:
          selector: entry_date
