name: Dagster Cloud CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Set up Docker registry access
      # See https://github.com/docker/login-action for more examples
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/624231820004/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'service-account@teamster-332318.iam.gserviceaccount.com'
      
      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Run Dagster Cloud CI/CD action
        uses: dagster-io/dagster-cloud-cicd-action/deploy@v0.2.2
        with:
          location-file: locations.yaml
          # Insert your Dagster Cloud Dagit URL here
          dagit-url: https://kipptaf.dagster.cloud/prod
          api-token: ${{ secrets.DAGSTER_AGENT_TOKEN }}
